function LoginGUI()
    % LoginGUI - 水下机器人控制系统登录界面
    % 海洋主题深色风格，支持用户名/密码验证

    % ---- 颜色主题 ----
    C.bg        = [0.04  0.10  0.18];   % 深海背景
    C.panel     = [0.06  0.14  0.24];   % 面板背景
    C.accent    = [0.00  0.60  0.90];   % 亮蓝强调色
    C.accentDk  = [0.00  0.40  0.65];   % 深蓝强调色
    C.text      = [0.85  0.95  1.00];   % 主文字
    C.subtext   = [0.50  0.70  0.85];   % 辅助文字
    C.border    = [0.10  0.28  0.46];   % 边框
    C.success   = [0.10  0.80  0.50];   % 成功绿
    C.error     = [1.00  0.35  0.35];   % 错误红
    C.inputBg   = [0.08  0.18  0.30];   % 输入框背景

    % ---- 预设账号 (用户名:密码) ----
    validUsers = containers.Map({'admin','pilot','guest'}, ...
                                {'admin123','pilot456','guest'});

    % ---- 主窗口 ----
    fig = uifigure('Name', '水下机器人控制系统 — 登录', ...
        'Position',       [100 100 520 400], ...
        'Color',          C.bg, ...
        'Resize',         'off', ...
        'CloseRequestFcn', @onClose);
    movegui(fig, 'center');

    % ---- 波浪装饰（用坐标轴绘制） ----
    ax = uiaxes(fig, 'Position', [0 0 520 400], ...
        'Color', C.bg, 'XColor', C.bg, 'YColor', C.bg, ...
        'XLim', [0 520], 'YLim', [0 400]);
    ax.Toolbar.Visible = 'off';
    disableDefaultInteractivity(ax);

    % 绘制装饰波浪
    x = linspace(0, 520, 400);
    for i = 1:3
        amp   = 12 - i * 3;
        freq  = 0.012 + i * 0.003;
        phase = i * 1.2;
        y1 = 60 + amp * sin(x * freq + phase);
        y2 = zeros(size(x)) + 0;
        patch(ax, [x, fliplr(x)], [y1, fliplr(y2)], ...
            C.accent - i*0.15, 'EdgeColor', 'none', ...
            'FaceAlpha', 0.12 - i*0.02);
    end

    % 绘制顶部装饰带
    patch(ax, [0 520 520 0], [370 370 400 400], C.accentDk, ...
        'EdgeColor', 'none', 'FaceAlpha', 0.6);

    % 顶部图标/标题装饰圆
    theta = linspace(0, 2*pi, 60);
    for r = [34 30 26]
        line(ax, 260 + r*cos(theta), 330 + r*sin(theta), ...
            'Color', [C.accent, 0.4 - (34-r)*0.08], 'LineWidth', 1.2);
    end
    % 潜水艇图标（简化）
    patch(ax, 260 + 18*cos(theta), 330 + 10*sin(theta), ...
        C.accent, 'EdgeColor', 'none', 'FaceAlpha', 0.85);
    patch(ax, [243 277 277 243], [327 327 334 334], C.accentDk, ...
        'EdgeColor', 'none');
    patch(ax, [256 264 264 256], [334 334 342 342], C.accentDk, ...
        'EdgeColor', 'none');
    text(ax, 260, 330, '⊕', 'Color', C.bg, 'FontSize', 16, ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold');

    % ---- 系统标题 ----
    uilabel(fig, 'Text', '水下机器人控制系统', ...
        'Position',           [60 285 400 32], ...
        'FontSize',           22, ...
        'FontWeight',         'bold', ...
        'FontColor',          C.text, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor',    'none');

    uilabel(fig, 'Text', 'Underwater Robot Control System', ...
        'Position',           [60 265 400 20], ...
        'FontSize',           11, ...
        'FontColor',          C.subtext, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor',    'none');

    % ---- 分割线 ----
    uipanel(fig, 'Position', [80 258 360 1], ...
        'BackgroundColor', C.border, 'BorderType', 'none');

    % ---- 用户名 ----
    uilabel(fig, 'Text', '用户名', ...
        'Position',   [100 225 80 20], ...
        'FontSize',   12, ...
        'FontColor',  C.subtext, ...
        'BackgroundColor', 'none');

    edtUser = uieditfield(fig, 'text', ...
        'Position',           [100 200 320 30], ...
        'FontSize',           13, ...
        'BackgroundColor',    C.inputBg, ...
        'FontColor',          C.text, ...
        'Value',              'admin', ...
        'Placeholder',        '请输入用户名', ...
        'HorizontalAlignment','left');

    % ---- 密码 ----
    uilabel(fig, 'Text', '密  码', ...
        'Position',   [100 165 80 20], ...
        'FontSize',   12, ...
        'FontColor',  C.subtext, ...
        'BackgroundColor', 'none');

    edtPass = uieditfield(fig, 'password', ...
        'Position',           [100 140 320 30], ...
        'FontSize',           13, ...
        'BackgroundColor',    C.inputBg, ...
        'FontColor',          C.text, ...
        'Placeholder',        '请输入密码');

    % ---- 状态提示标签 ----
    lblStatus = uilabel(fig, 'Text', '', ...
        'Position',           [100 112 320 22], ...
        'FontSize',           11, ...
        'FontColor',          C.error, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor',    'none');

    % ---- 登录按钮 ----
    btnLogin = uibutton(fig, 'push', ...
        'Text',               '登  录', ...
        'Position',           [100 72 320 34], ...
        'FontSize',           14, ...
        'FontWeight',         'bold', ...
        'BackgroundColor',    C.accent, ...
        'FontColor',          [1 1 1], ...
        'ButtonPushedFcn',    @onLogin);

    % 账号提示
    uilabel(fig, 'Text', '演示账号：admin / admin123    pilot / pilot456    guest / guest', ...
        'Position',           [60 30 400 20], ...
        'FontSize',           9, ...
        'FontColor',          C.subtext, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor',    'none');

    % ---- 应用中文字体（防止乱码）----
    applyFont(fig, getCJKFont());

    % ---- 回调函数 ----
    function onLogin(~, ~)
        username = strtrim(edtUser.Value);
        password = strtrim(edtPass.Value);

        if isempty(username)
            lblStatus.Text      = '⚠  请输入用户名';
            lblStatus.FontColor = C.error;
            return;
        end

        if validUsers.isKey(username) && strcmp(validUsers(username), password)
            lblStatus.Text      = '✔  验证成功，正在启动系统…';
            lblStatus.FontColor = C.success;
            btnLogin.Enable     = 'off';
            drawnow;
            pause(0.8);
            close(fig);
            MainDashboard(username);
        else
            lblStatus.Text      = '✘  用户名或密码错误，请重试';
            lblStatus.FontColor = C.error;
            edtPass.Value       = '';
        end
    end

    function onClose(~, ~)
        delete(fig);
    end
end
